apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
name: cleanup
spec:
workspaces:
- name: source
steps:
- name: cleanup-step
image: alpine:3.18
script: |
#!/bin/sh
echo "Cleaning workspace..."
rm -rf /workspace/source/*

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
name: run-tests
spec:
workspaces:
- name: source
steps:
- name: run-nose-tests
image: python:3.9
script: |
#!/bin/sh
echo "Installing dependencies..."
pip install nose
echo "Running tests..."
nosetests
